X = int(input(" Enter the first number: "))
Y = int(input(" Enter the second number: "))
a =(X+Y)
s =(X-Y)
m =(X*Y)
d =(X/Y)
print("Addition:",a )
print("Subtraction:",s)
print("Multiplication:",m)
print("Division:",d)